<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DropdownListsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        // \DB::table('dropdown_lists')->delete();
        
        \DB::table('dropdown_lists')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Regional Standards And Testing Laboratories',
                'code' => 'RSTL',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Agency Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:50',
                'updated_at' => '2021-01-13 17:18:28',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Research And Development Institutes',
                'code' => 'RDI',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Agency Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:50',
                'updated_at' => '2020-12-08 09:56:04',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Regional Metrology Lab',
                'code' => 'RML',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Agency Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:50',
                'updated_at' => '2020-12-08 09:56:05',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Regional Volumetric Calibration Laboratory',
                'code' => 'RVCL',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Agency Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:50',
                'updated_at' => '2020-12-08 09:56:06',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Cavite Water & Wastewater Testing Laboratory',
                'code' => 'CWWTL',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Agency Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:50',
                'updated_at' => '2020-12-03 13:13:50',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Private Sector',
                'code' => 'PS',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Agency Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:50',
                'updated_at' => '2020-12-03 13:13:50',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Raw And Processed Food',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Marine Products',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Canned / Bottled Fish',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Fishmeal',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Seaweeds',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Petroleum Products / Haulers',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Mining',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Hospitals',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Academe / Students',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Beverage And Juices',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Government / Lgus',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Construction',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Water Refilling / Bottled Water',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Students',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Private Individual',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Bussiness Nature',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:15',
                'updated_at' => '2020-12-03 13:14:15',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Students / Researchers',
                'code' => 'n/a',
                'percentage' => 25,
                'description' => 'n/a',
                'type' => 'Discount',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:49',
                'updated_at' => '2020-12-03 13:14:49',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Senior Citizen',
                'code' => 'n/a',
                'percentage' => 20,
                'description' => 'n/a',
                'type' => 'Discount',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:49',
                'updated_at' => '2020-12-03 13:14:49',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Person With Disability',
                'code' => 'n/a',
                'percentage' => 20,
                'description' => 'n/a',
                'type' => 'Discount',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:49',
                'updated_at' => '2020-12-03 13:14:49',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Employee',
                'code' => 'n/a',
                'percentage' => 50,
                'description' => 'n/a',
                'type' => 'Discount',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:49',
                'updated_at' => '2020-12-03 13:14:49',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Fully Subsidized',
                'code' => 'n/a',
                'percentage' => 100,
                'description' => 'n/a',
                'type' => 'Discount',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:49',
                'updated_at' => '2020-12-03 13:14:49',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'In-house',
                'code' => 'n/a',
                'percentage' => 20,
                'description' => 'n/a',
                'type' => 'Discount',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:49',
                'updated_at' => '2020-12-03 13:14:49',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'No Discount',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Discount',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:49',
                'updated_at' => '2020-12-03 13:14:49',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Food Processing',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Industry Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:19',
                'updated_at' => '2020-12-03 13:14:19',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Furniture',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Industry Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:19',
                'updated_at' => '2020-12-03 13:14:19',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Aquatic And Marine',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Industry Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:19',
                'updated_at' => '2020-12-03 13:14:19',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Horticulture',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Industry Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:19',
                'updated_at' => '2020-12-03 13:14:19',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Metals And Engineering',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Industry Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:19',
                'updated_at' => '2020-12-03 13:14:19',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Information And Communcations Technology',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Industry Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:19',
                'updated_at' => '2020-12-03 13:14:19',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Health Products And Services',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Industry Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:19',
                'updated_at' => '2020-12-03 13:14:19',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Gthd',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Industry Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:19',
                'updated_at' => '2020-12-03 13:14:19',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Chemical Laboratory',
                'code' => 'CHE',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-03 13:14:02',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Microbiological Laboratory',
                'code' => 'MIC',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-03 13:14:02',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Metrology Laboratory',
                'code' => 'MET',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-03 13:14:02',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Physical Laboratory',
                'code' => 'PHY',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 11:05:16',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Formula of Conversion',
                'code' => 'FOC',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:20',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Shelf Life Testing',
                'code' => 'SHL',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:23',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Biological Laboratory',
                'code' => 'BIO',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:23',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Gamma or Electron Beam Irradiation Facilities',
                'code' => 'GEB',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:23',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Pulp and Paper Testing Laboratory',
                'code' => 'PPTL',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:24',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Plywood Testing Laboratory',
                'code' => 'PLY',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:25',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Physical and Performance Testing Laboratory',
                'code' => 'PPT',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:26',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Furniture Testing Laboratory',
                'code' => 'FTC',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:26',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Mechanical Metallurgy Laboratory',
                'code' => 'MML',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:26',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Physico-Chemical Laboratory',
                'code' => 'PCL',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:28',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Corrosion Laboratory',
                'code' => 'COR',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:28',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Halal Verification Laboratory',
                'code' => 'HAL',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:30',
            ),
            52 => 
            array (
                'id' => 53,
            'name' => 'Organic Chemistry Laboratory (ITDI)',
                'code' => 'OCS',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:30',
            ),
            53 => 
            array (
                'id' => 54,
            'name' => 'Inorganic Chemistry Laboratory (ITDI)',
                'code' => 'ICS',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:31',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Pharmacology and Toxicology Laboratory',
                'code' => 'PTS',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:31',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Radiation Protection Services',
                'code' => 'RPS',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:32',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Advance Device and Materials Testing Laboratory',
                'code' => 'ADMATEL',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:34',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'National Metrology Lab',
                'code' => 'NML',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:34',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Packaging Testing Division',
                'code' => 'PTD',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:35',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Nuclear Analytical Techniques Application Section',
                'code' => 'NATA',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:36',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Biochemical Laboratory',
                'code' => 'BIOCHE',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:36',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Rubber Testing Laboratory',
                'code' => 'RTL',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:37',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Auto-Parts Testing Laboratory',
                'code' => 'ATL',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:38',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Instrumentation Laboratory',
                'code' => 'INS',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:38',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Non-Destructive Testing Laboratory',
                'code' => 'NDT',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Laboratory',
                'status' => 1,
                'created_at' => '2020-12-03 13:14:02',
                'updated_at' => '2020-12-08 09:56:39',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Academic',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Purpose',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:07',
                'updated_at' => '2020-12-03 13:14:07',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'Research And Development',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Purpose',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:07',
                'updated_at' => '2020-12-03 13:14:07',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Tariff / Registration',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Purpose',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:07',
                'updated_at' => '2020-12-03 13:14:07',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'Nutrition Labeling',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Purpose',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:07',
                'updated_at' => '2020-12-03 13:14:07',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Bidding',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Purpose',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:07',
                'updated_at' => '2020-12-03 13:14:07',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Quality Evaluation',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Purpose',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:07',
                'updated_at' => '2020-12-03 13:14:07',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'Ra 9242 Certification',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Purpose',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:07',
                'updated_at' => '2020-12-03 13:14:07',
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'Regulatory',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Purpose',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:07',
                'updated_at' => '2020-12-03 13:14:07',
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'Export',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Purpose',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:07',
                'updated_at' => '2020-12-03 13:14:07',
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'Pick Up',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Mode of Release',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:45',
                'updated_at' => '2020-12-03 13:14:45',
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'Delivery',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Mode of Release',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:45',
                'updated_at' => '2020-12-03 13:14:45',
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'Mail',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Mode of Release',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:45',
                'updated_at' => '2020-12-03 13:14:45',
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'Fax',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Mode of Release',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:45',
                'updated_at' => '2020-12-03 13:14:45',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'Local',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Request Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:53',
                'updated_at' => '2020-12-03 13:13:53',
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'Referral',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Request Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:53',
                'updated_at' => '2020-12-03 13:13:53',
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'Cash',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Payment Mode',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:52',
                'updated_at' => '2020-12-03 13:14:52',
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'Cheque',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Payment Mode',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:52',
                'updated_at' => '2020-12-03 13:14:52',
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'Money Order',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Payment Mode',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:52',
                'updated_at' => '2020-12-03 13:14:52',
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'Individual',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Classification',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:29',
                'updated_at' => '2020-12-03 13:14:29',
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'Firm',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Classification',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:29',
                'updated_at' => '2020-12-03 13:14:29',
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'Analysis Fee',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Collection Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:57',
                'updated_at' => '2020-12-13 10:03:41',
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'Customer Wallet',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Collection Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:57',
                'updated_at' => '2020-12-03 13:14:57',
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'Bureau Of Treasury',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Deposit Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:15:01',
                'updated_at' => '2020-12-03 13:15:01',
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'Project',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Deposit Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:15:01',
                'updated_at' => '2020-12-03 13:15:01',
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'Setup Core',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Customer Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:23',
                'updated_at' => '2020-12-03 13:14:23',
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'Non Setup',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Customer Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:23',
                'updated_at' => '2020-12-03 13:14:23',
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'Setup Non-core',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Customer Type',
                'status' => 0,
                'created_at' => '2020-12-03 13:14:23',
                'updated_at' => '2020-12-03 13:14:23',
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'In House',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Request From',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:57',
                'updated_at' => '2020-12-03 13:13:57',
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'Pstc',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Request From',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:57',
                'updated_at' => '2020-12-03 13:13:57',
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'General Fund',
                'code' => 'GF',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'OR Category',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:57',
                'updated_at' => '2020-12-03 13:13:57',
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'Trust Fund',
                'code' => 'TF',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'OR Category',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:57',
                'updated_at' => '2020-12-03 13:13:57',
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'Default',
                'code' => 'n/a',
                'percentage' => 0,
                'description' => 'n/a',
                'type' => 'Default',
                'status' => 0,
                'created_at' => '2020-12-03 13:13:57',
                'updated_at' => '2020-12-03 13:13:57',
            ),
        ));
        
        
    }
}